### ISSUE TITLE
Reopen previously open documents

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#229]

**Comment by mcackay** [comment]
Hi @jurplel -- just came across qView, and so far looks great.

However for me the app is not re-opening previously-open images.  If I have 3 images open, quit the app and re-launch, i end up just with a black qView window.

I see this enhancement request was marked as Completed in May.
Is there a setting I'm missing somewhere which will enable this functionality?

'Save recent files' is checked in the settings ... but i presume that only is controlling the 'Open Recent ...' submenu contents.

Currently running version 6.1.

**Comment by jdpurcell** [comment]
@mcackay qView does not have this feature currently; I believe this issue was closed just because it was a duplicate of #369. That said, I have working code that accomplishes this on macOS (I don't think it makes sense on other platforms) and would be willing to contribute it as a pull request, but it depends on some other code I wrote that hasn't been fully reviewed/accepted yet.

**Comment by jurplel** [comment]
Sorry for improperly labeling this issue.

There is another issue open for this functionality.
