### ISSUE TITLE
Support fractional scroll steps

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#266]
This will require a significant rework of the zoom mechanism

**Comment by porg** [comment]
Possibly helpful for planning/organizing: I have cross-read a lot of issues and I guess this is the technical foundation for #170 

I have done a thorough cross-reading of issues before submitting my issue compilation, which I announced in #416 intended to work as a cover letter from me to the qView community and to you @jurplel as its maintainer.

I wanted to file: "Support for full trackpad input resolution for butter-smooth zooming/scrolling/rotating" … instead of 1990ies mousewheel emulation.

But then realized this is a sub issue of the overall  #170.

I guess "fractional scrolling" means specifically butter smooth scrolling (felt as a continuum rather than noticable intermediate steps) as a rendering capability which itself can take the user input of a "high resolution trackpad".

If you manage to pull this off then on devices with hi-res trackpad input then I recommend the "Zoom Amount" setting to remain as a way to fine tune the zoom sensitivity. Instead of "1 mouse wheel tick equals that percentage of zoom-factor" as it seems to do currently.

**Comment by jurplel** [comment]
Yes, there is a significant rework of the entire qvgraphicsview coming for 6.0 with all the smoothness that one would want and expect from modern software (hopefully even pretty animations for zooming and scrolling!)

It is important that you noted to remember trackpad sensitivity, though.

**Comment by jurplel** [comment]
I gave the original intent of this issue (small scrolling steps) a go with my mouse, and I have to say it feels frustrating and useless because it takes away the distinct scrolling steps. wontfix unless anyone needs this
