### ISSUE TITLE
apng format support

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#280]

**Comment by sonulohani** [comment]
We have **apng** plugin support in Qt. Here is the source code of the plugin:- https://github.com/Skycoder42/QtApng/tree/master/src/plugins/imageformats/apng

**Comment by jurplel** [comment]
Yes that is the plan.

**Comment by sonulohani** [comment]
Hi @jurplel 

I am able to load apng file successfully. I can see the png file getting animated. For that we need to compile the plugin and put that in plugins/imageformats folder in Qt SDK directory. 

The problem is that ```QImageReader::supportsAnimation()``` returns false for apng file. I believe we might need to **modify/add this as an issue** in the plugin repository. 

I thought of removing the QImageReader::supportsAnimation() with QMovie::isValid(). However, it returns true even for normal image file which doesn't have animations. So I replaced it with ```loadedMovie.isValid() && loadedMovie.frameCount() != 1``` and this works fine.

**Comment by sonulohani** [comment]
Here is the PR:- https://github.com/jurplel/qView/pull/325

**Comment by jurplel** [comment]
Only took a quick look at this but I have no idea how `QImageReader::supportsAnimation()` could not be working.

https://code.woboq.org/qt5/qtbase/src/gui/image/qimagereader.cpp.html#_ZNK12QImageReader17supportsAnimationEv

`QImageReader::supportsAnimation()` simply queries `supportsOption(QImageIOHandler::Animation).

https://github.com/Skycoder42/QtApng/blob/master/src/plugins/imageformats/apng/apngimagehandler.cpp#L50

`supportsOption` is written to return true for `QImageIOHandler::Animation` (unless this bit of code is invalid in a way I cannot see).

Are you using it with a `.apng` file extension or a `.png` file extension? It notes in the [readme](https://github.com/Skycoder42/QtApng) that it only works with `.apng`. I am guessing you probably did use an `.apng` file extension though because it seems to imply that it would not work whatsoever with `.png`.

**Comment by sonulohani** [comment]
Hi @jurplel 

Yes, youre right. If you see the code change I am explicitly setting the fomat to apng. This would not work with png files because Qt already has plugin available to support png files. The only way I would see to fix is either use our own image reader which would based on the frames count use png or apng. I will explore more on this.

**Comment by jurplel** [comment]
I have opened an issue for some of the weirdness: https://github.com/Skycoder42/QtApng/issues/11

**Comment by BLumia** [comment]
https://github.com/jurplel/qView/blob/8ba016b518eb45c8d954f050d0dea706afc2962f/src/qvimagecore.cpp#L113

By looking at the current implementation of qView, I guess the `supportsAnimation()` issue is related to https://github.com/Skycoder42/QtApng/pull/12 which should be fixed now :)

The `size` image property is still not correct but it's a different issue of QtApng IMO.

**Comment by jurplel** [comment]
Oh, cool!
