### ISSUE TITLE
Holding down an arrow key should scroll through images as fast as possible

### ISSUE THREAD

**Issue by georgemorgan** [jurplel/qView#310]
Like in Preview, when you hold down an arrow key, it loads and displays the images as fast as it can. This behavior should be duplicated in qView. It is impossible to scroll through large numbers of images needing to press the arrow key once every frame.

**Comment by jurplel** [comment]
It _should_ already do that and it certainly does on my side. Can you provide any more information that could be relevant? Are you using a nightly build or the release version?

**Comment by georgemorgan** [comment]
I am using the latest cask installed via brew. I will try building nightly and see if it is fixed.

**Comment by jurplel** [comment]
there is a pre-built one here: https://dev.azure.com/jurplel/qView/_build/results?buildId=409&view=artifacts&type=publishedArtifacts

It definitely should be working on the release build.

**Comment by georgemorgan** [comment]
Something even worse happens on that build. It just opens every image in a separate window.

I'm on the latest macOS Catalina if that helps.

**Comment by georgemorgan** [comment]
If I open the qView binary directly and pass a glob as the first argument it opens all of them in the same window. But not from Finder, which worked on the homebrew cask version. Also, it seems to do like 3 frames at a time now on this build, but then seems to stop once it hits an image that hasn't been loaded. I'm trying to open 200 images.

**Comment by jurplel** [comment]
Can you maybe record a video?

**Comment by georgemorgan** [comment]
I've attached a zip with a movie of the bug. I hold on the right arrow key and the frames change, and then it stops, even if I keep holding. So I let go and when I press it again it changes a few more frames, but then the same thing happens.

[bug.mov.zip](https://github.com/jurplel/qView/files/4565967/bug.mov.zip)

**Comment by jurplel** [comment]
Try changing Preloading to extended in the preferences and see if that makes a difference

**Comment by georgemorgan** [comment]
That video was taken with extended set for preloading.

**Comment by jurplel** [comment]
Are you reading off of a slower storage device like an external drive? Does your CPU usage max out?

**Comment by jurplel** [comment]
Are you sure that the images will never switch if you keep holding the arrow key? It may be that the caching threads are cannibalizing the image-load threads

**Comment by georgemorgan** [comment]
Reading from the internal SSD on a 2017 MBPR, so I don’t think read speed is the issue. CPU percent is less than 10% for everything running. qView CPU usage is negligible. And yes, I’m 100% positive that no matter how long I hold the arrow key it only loads like 3 frames. Granted I’ve only held it for a max of like 30s but I think that’s enough to prove the theory.

**Comment by jurplel** [comment]
Does it change if you use a different set of files?

**Comment by georgemorgan** [comment]
I tried it again yesterday with a different set of files and had the same problem. The files were also a different size, and 16-bit PNG instead of 8-bit PNG - but it didn’t make a difference.

**Comment by jurplel** [comment]
Does the problem still present with a fresh qView configuration?

**Comment by georgemorgan** [comment]
How can I clear it?

**Comment by jurplel** [comment]
You can just use restore defaults in the preferences menu, or for good measure you can delete the file which should be located at: `$HOME/Library/Preferences/` named qView something.

**Comment by fullmooooon** [comment]
I have the same needs. I try to use nw.js To create an image viewer with this feature, but it failed in the end, because I couldn't completely remove the image decode time of chrome.
The following is my attempt to use QView.
I have dozens of 8K resolution PNG images (most of them are more than 10m) under one folder. Whether it is advanced or extended preloading mode, using QView to switch quickly will cause hundreds of milliseconds of loading delay.
I also tried to convert PNG images into avif format, and the final size of these images was about 1m. This looks cool, but the load latency can grow to about 8 times more unbearable.
I know nothing about C + +. I guess QView only preloads the images and doesn't decode them. Hope to help you.

**Comment by jurplel** [comment]
It is certainly true that plugin-based formats like AVIF take way longer. With those large files, it's likely that qView avoided preloading them because they are too large. Clearly some fine-tuning could be done here.

**Comment by fullmooooon** [comment]
What I want to say is not avif, I want to completely preload and predecode images, just like switching windows smoothly under Windows 10. I know that minimal is one of the advantages of QView, but can it provide such an option.
I don't mind the memory footprint at all. Preload is an important part, but in some cases the decoding time will take up 98% of the total time. Zero time delay browsing experience will make QView better.
Thank you for your reply

**Comment by jurplel** [comment]
I believe if it actually chooses to preload it, it will be predecoded as well. I will look into this further later on. I love zero time delay too, and it does work as expected on smaller images, so I think it may just be a maximum size check limiting things for the sake of memory.

**Comment by eugenesvk** [comment]
@jurplel there might be a general issue not related to size, I've tested the speed of png→avif switch on files as small as 70k (avif) and there is still a significant delay

On the other hand, in qimgv there is 0 delay if preloading has done its job (e.g. I view the png image for a short while giving preloading some time to work, then switch, 0 delay), and without preloading the delay is there, but is much shorter than in your app (e.g. if I have `1.png`, `2.png` and `3.avif` and quickly cycle from 1 through 2 to 3, so that preloading hasn't had a change to kick in, it's not 0-delay anymore)

Just for comparison on an old Windows machine: a non-preloaded (switching from file 1.png to file 2.png to file 3.avif) delay in qimgv is ~0.5sec and ~2.4 sec in qView (recorded videos and timed between the second key-up and the avif image appearing)

**Comment by jurplel** [comment]
> @jurplel there might be a general issue not related to size, I've tested the speed of png→avif switch on files as small as 70k (avif) and there is still a significant delay
> 
> On the other hand, in qimgv there is 0 delay if preloading has done its job (e.g. I view the png image for a short while giving preloading some time to work, then switch, 0 delay), and without preloading the delay is there, but is much shorter than in your app (e.g. if I have `1.png`, `2.png` and `3.avif` and quickly cycle from 1 through 2 to 3, so that preloading hasn't had a change to kick in, it's not 0-delay anymore)
> 
> Just for comparison on an old Windows machine: a non-preloaded (switching from file 1.png to file 2.png to file 3.avif) delay in qimgv is ~0.5sec and ~2.4 sec in qView (recorded videos and timed between the second key-up and the avif image appearing)

Interesting, it is possible this will be fixed in qView due to some minor changes in the preloading algorithm

**Comment by jurplel** [comment]
Closing since this is an old issue, feel free to reopen
