### ISSUE TITLE
Segmentation fault on wayland

### ISSUE THREAD

**Issue by arun54321** [jurplel/qView#327]
**Environment:**
- OS: Arch Linux
- qView version: latest git build

**Information:**
It happens on wayland only. I have to remove configuration file to make it work again.
[trace](https://del.dog/emogryxith)

**Comment by sonulohani** [comment]
Hi @arun54321 
Could you please share your config file as well.

**Comment by arun54321** [comment]
@sonulohani https://pastebin.pl/view/46f11012

**Comment by jurplel** [comment]
What desktop environment/compositor?

**Comment by arun54321** [comment]
KDE kwin Wayland.

**Comment by jurplel** [comment]
I can't seem to reproduce it :/

**Comment by jurplel** [comment]
Closed due to inactivity and failure in reproducing the issue.

**Comment by CoolingTool** [comment]
If anyone ever sees this issue again I fixed this by changing "Window matches image size" to Never

**Comment by jurplel** [comment]
That's good to know!

**Comment by wsdfhjxc** [comment]
Okay, so @CoolingTool's workaround is a nice find. Also, one thing I noticed is that once the bug happens, and it's no longer possible to open any image, it can be fixed by removing the `geometry=@ByteArray(...)` line in the qView.conf file. So it seems it has something to do with reading and applying corrupted window geometry data, and that's why the program crashes.

**Comment by jurplel** [comment]
AFAIK wayland doesn't like setting window geometry, so that is probably why this occurs
