### ISSUE TITLE
Opening Options resets the zoom 

### ISSUE THREAD

**Issue by sonulohani** [jurplel/qView#336]
**Environment:**
- OS: Windows 10
- qView version: latest master

**Information:**
1. Open qView.exe
2. Open an image
3. Zoom in or zoom out the image.
4. Open options 

Actual Behavior: Zoom resets.
Expected Behavior: Image should be shown in either zoom in or zoom out based on **point 3**

**Comment by jurplel** [comment]
Confirmed

**Comment by jurplel** [comment]
Resolved: https://github.com/jurplel/qView/commit/756ff48987ad9183662ace04fcc3fae12cb5a7db
It was caused because opening the settings window triggers the settings to load from the config file. When the settings load from the config file, the scale resets to apply the new settings without bugs.

I have mitigated the issue by only sending out the `settingsUpdated()` signal when the settings were actually updated. In addition, I have made it so that giving the application focus will trigger settings loading from file.

Thanks for another great bug report.
