### ISSUE TITLE
Crashed when opening preferences

### ISSUE THREAD

**Issue by shape55** [jurplel/qView#368]
Here's a crash report that occurred when opening the preferences when 1 image was open.  However, I'm not able to reproduce it.

https://pastebin.com/zKeNVytd

- macOS 10.15.7 Catalina, MacBook Pro 16" (Late 2019)
- qView 4.0

**Comment by jurplel** [comment]
I assume what's going on here is that the options dialog has been opened once, and since `Qt::WA_DeleteOnClose` is set on QVOptionsDialog, it will delete itself when it is closed. However, the pointer in qvapplication does not clear when Qt deletes it automatically, so it becomes a source of undefined behavior (in an unpredictable way).

**Comment by jurplel** [comment]
the pointer should be set to null by the QDialog::finished connection, but i guess it slipped through somehow...
An easy fix would be changing the pointer to qpointer.

**Comment by jurplel** [comment]
Okay, here's how to reproduce:
1. Open a window
2. Open a preferences dialog from a source tied to that window
3. Close the window (This close the preferences dialog because the window is passed as its parent, which is a bug on mac!!)
4. Open a new preferences dialog, and as the pointer is not set to nullptr, the program will segfault as described.

Good. Confirmed. Thanks for your report.
