### ISSUE TITLE
Translation questions

### ISSUE THREAD

**Issue by smarquespt** [jurplel/qView#377]
Hi, there are some strings in source file that confuses me. Can you give help?

../src/qvoptionsdialog.ui:363 - Image resizes &past actual size

This text seems ackward.

../src/qvoptionsdialog.ui:379 ../src/qvoptionsdialog.ui:401 - Ignores select sides of an image when fitting to window (some sides will extend beyond the window boundaries)

What is "...select sides..."?

../src/qvoptionsdialog.ui:427 - Zoom &towards cursor

???

../src/qvoptionsdialog.ui:424 - Choose whether or not zooming in and out above 100% zoom will zoom towards the cursor

What is "...zoom towars cursor..."

Another thing is that I see pt and pt_PT. I've uploaded pt_PT to pt and I think you should remove pt_PT. This way, anyone using pt_XXX can benefir from pt translation if there is nome for pt_XXX

**Comment by jurplel** [comment]
1. That is somewhat awkward text, but I'm not sure how to communicate it effectively. The option is a checkbox, where if it is checked, the 0% zoom state of the image never gets larger than the image's original size.
2. Select sides refers to the horizontal edges or the vertical edges, based on the user's selection.
3. "Zoom towards cursor" refers to the behavior when you use the scroll wheel to zoom. It will zoom with the focal point being the cursor's position, instead of directly in the center of the image.
4. I think I answered this in 3
5. I was unsure what would be best, but based on your response [here](https://github.com/jurplel/qView/issues/252#issuecomment-722125181), I figured it would be better to be specific. If you think that using a generic pt is better, I am all for it.

Sorry for the confusion, I hope I was able to answer your questions effectively.

**Comment by smarquespt** [comment]
> 1. That is somewhat awkward text, but I'm not sure how to communicate it effectively. The option is a checkbox, where if it is checked, the 0% zoom state of the image never gets larger than the image's original size.

ok, 
> 2. Select sides refers to the horizontal edges or the vertical edges, based on the user's selection.

Why not using borders or margins instead?

> 3. "Zoom towards cursor" refers to the behavior when you use the scroll wheel to zoom. It will zoom with the focal point being the cursor's position, instead of directly in the center of the image.
> 4. I think I answered this in 3

Ok

> 5. I was unsure what would be best, but based on your response [here](https://github.com/jurplel/qView/issues/252#issuecomment-722125181), I figured it would be better to be specific. If you think that using a generic pt is better, I am all for it.

Please do.

> 
> Sorry for the confusion, I hope I was able to answer your questions effectively.
