### ISSUE TITLE
qView window gets unmaximized after exiting full screen

### ISSUE THREAD

**Issue by floorcat** [jurplel/qView#453]
**Environment:**
- OS: Arch Linux
- qView version: git master branch (also happens on 4.0)
- Window Manager: Happens on both: KWin and Openbox

**Information:**
Steps to reproduce: Maximize qView window -> go to full screen -> exit full screen -> now the window isn't maximized anymore

Seems to be the same problem as here: #332

**Comment by jurplel** [comment]
Literally no idea why this happens. I tried to fix it for a bit, but it seemed to be working at face value. Couldn't figure out when the maximized state was being removed.

**Comment by jdpurcell** [comment]
I can reproduce this on Windows. After some troubleshooting, I believe what's happening is that the `setWindowState` call to restore the maximized state doesn't take effect immediately, i.e. if you query `windowState` immediately after, it will return `WindowNoState`. The maximized window state isn't fully applied until Qt finishes processing its pending events. Since `MainWindow::setWindowSize` is called right after, it doesn't see that the window is maximized and proceeds to resize the window.

My thoughts on how to fix it are:

1. Do we even want to run `MainWindow::setWindowSize` after coming out of full screen? If "window matches image size" is set to "when opening images", this causes qView to auto-resize the window and forget its size prior to entering full screen. If we get rid of this call, that takes care of it.
2. Calling `qApp->processEvents()` right after `setWindowState` helps and seems to prove my theory, but it feels improper.
3. `MainWindow::setWindowSize` could be conditionally run with `if (!storedWindowState.testFlag(Qt::WindowMaximized))`.

**Comment by jurplel** [comment]
if 1 has no side effects, that should be good. I agree 2 feels improper, and might result in weird behavior on some platforms/configurations. 3 seems like the least likely to have side effects, if anything is iffy with option 1, but 1 seems fine.

**Comment by jdpurcell** [comment]
@jurplel Agreed, option 1 is the obvious choice for me. If there were side effects, they would already be happening with the other size matching settings ("Never" / "When launching"). I did a blame on the line in question and found it was added in https://github.com/jurplel/qView/commit/936df1529b87d7494ceedfc7cde8874b7fbd8957, which makes me wonder if it was simply left there by accident after a debugging session.
