### ISSUE TITLE
The Scaling Jitter Debacle

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#51]
There is a jitter that is most observable when slowly resizing the window with the scaling algorithm enabled. This is a difficult issue to solve

**Comment by jeep70** [comment]
Probably instead of fitting the full version in view right before making the scaled version, try to do that with math instead

**Comment by jeep70** [comment]
I implemented something to this effect in my local environment. It simply scales the original pixmap to the width or height of the window (whichever is lower) instead of messing around with scaling values. While being much more elegant, it still does jitter as this is likely due to the fitinview function more than anything else
