### ISSUE TITLE
Depending on the characters in the filename, it's slow.

### ISSUE THREAD

**Issue by Gttrdkn** [jurplel/qView#552]
windows 10 , 11 22H2
qView nightly version, from 2022-12-17.1 ?? to 2023-01-02.1

If the file name characters is like cjk(Chinese,  Japanese, Korean), not English, it takes at least twice as long to execute or load.

sample

è, �,世界 no problem.
ā,国 slow....

**Comment by jdpurcell** [comment]
I tried to reproduce this. I'm not sure if it's the same problem reported here, but I do see a delay (~600 ms) the first time Qt loads the font for Chinese characters. This might happen while loading an image, inside `QVInfoDialog::setInfo`, specifically the `window()->adjustSize()` call which loads the font to calculate text width. Or if an image hasn't been loaded, it can cause a delay the first time the "Open Recent" submenu is displayed, if any of those filenames contain Chinese characters. After that it's always fast though; the delay only happens again after closing and reopening qView.

This only happens if qView is compiled for Qt6, not Qt5, which could explain why it started happening in the nightly builds. That is assuming you are using the Windows 64-bit qView build. The 32-bit build is still using Qt5 so maybe it would be faster, if it is indeed the same problem.

**Comment by jurplel** [comment]
I'm nuking a lot of issues right now, so feel free to reopen this if it is still an issue, but IIRC we talked about this and either solved it or decided not to fix it for now?
