### ISSUE TITLE
"qView.app" can't be opened

### ISSUE THREAD

**Issue by Mehrshad-m2** [jurplel/qView#562]
"qView.app" can't be opened because Apple cannot check it for malicious software.
This software needs to be updated.

![Xnip2023-01-17_02-56-35](https://user-images.githubusercontent.com/122845425/212793234-9702897e-d816-4b94-b4e6-cfc7b37c484a.png)

**Environment:**
- OS: macOS 13.0.1 Ventura
- Device: MacBook Pro 13", M1, 2020
- qView version: v5.0

**Information:**
"qView.app" can't be opened because Apple cannot check it for malicious software. This software needs to be updated.
This software needs to be updated. Contact the developer for more intormation.
Says macOS after trying to run the app.

Please advice

Thank you so much

Best regards

**Comment by jdpurcell** [comment]
In Finder, instead of double clicking to launch the qView app, right click it and choose Open from the popup menu. Then a different dialog will appear and you can click the Open button. Then the qView window should appear.

This is only needed the first time when running qView. After that, macOS will remember that you authorized it to open and you can launch it the normal way.

**Comment by Mehrshad-m2** [comment]
Awesome. Thank you so much 🙏🏽
