### ISSUE TITLE
Features borrowed from Viewnior

### ISSUE THREAD

**Issue by Gabriel-p** [jurplel/qView#570]
First of all: thank you. I recently found qView and thank god I did because it is fast and simple and *fast* and it's the only good replacement for the (non GTK4) image viewer [Viewnior](https://siyanpanayotov.com/project/viewnior), and I tried basically everything else out there.

The only thing that I miss in qView is simple menu bar with a few buttons. This is what Viewnior showed, basically previous and next buttons and some zoom buttons (the rotate buttons are not all that necessary). Also the zoom percentage info would be a nice addition and maybe an option to update the image with F5?

![vnr_normal_mode_2](https://user-images.githubusercontent.com/6054951/217324592-8bf66c24-394c-4cc4-a4b5-3d96aa596cfd.png)

I know you can move left and right with the keyboard arrows but having a way to do it with the mouse is something I miss.

That's it. Thank you again!

**Comment by jurplel** [comment]
I think zoom percentage info is planned at this point. 

F5 to refresh the image is a good idea, I will make a separate issue: #587.

The bar of icon actions I don't think will ever make it to qView. It's not like an invalid suggestion or anything, it just goes against my vision for the software. Might be territory for a fork.

I am glad qView has been serving you well otherwise!

**Comment by jurplel** [comment]
I understand where you're coming from, but as I said I don't plan to add it for now.

If you have a 5-button mouse, you can use the back/forward buttons on the mouse to go to the previous and next image.
