### ISSUE TITLE
Unable to view .ico file format

### ISSUE THREAD

**Issue by ArkitectNaut** [jurplel/qView#572]
**Environment:**

- OS: Windows 11 
- qView version: 5.0

**Information:**

Opening .ico files shows an image for a fraction of a second before blanking out. Also, that millisecond preview doesn't show the highest quality version of the file, contrarily to what seems to be the intended functionality from what I gathered in #305.

![qView_Blank](https://user-images.githubusercontent.com/92726010/218304413-b77f0e16-b33e-469d-85c1-0f82fa802a9f.jpg)
![qView_Info](https://user-images.githubusercontent.com/92726010/218304415-5af91aff-511c-4176-8340-3e1296f6bf39.jpg)

**Comment by jdpurcell** [comment]
@jurplel This happens when "Image scaling" is enabled (or even when it's not, if invoking "Original size"). The problem is, `currentFileDetails.isMovieLoaded` is `true` even though it ends up not being a valid movie. Although `QMovie::isValid` initially returns true, `QMovie::start` fails and causes `QMovie::isValid` to start returning `false`. `QMovie::state` also returns `QMovie::MovieState::NotRunning` when this happens. [This fixes it](https://github.com/jdpurcell/qView/commit/6304310d84091c15beb513c1ed3088f54ec1803f) for me.

As for picking the highest resolution image, I couldn't figure out how to do it. `QImageReader::imageCount` returns more than one, but I didn't have any luck loading anything other than the first, whether it was by calling `QImageReader::read` repeatedly, `QImageReader::jumpToNextImage`, or `QImageReader::jumpToImage`.

**Comment by ArkitectNaut** [comment]
Not sure how useful this is but opening the .ico files in Firefox results in the highest quality being displayed. The best outcome would be something similar to how Preview on MacOS shows all the various quality versions of the .icns format.

Also, your fix totally works. Thanks!
