### ISSUE TITLE
Support for ARM64 Windows

### ISSUE THREAD

**Issue by etienne51** [jurplel/qView#583]
Would it be possible to get a .exe installer for a version supporting the ARM64 Windows platform? I can run the x64 version when downloading standalone (the installer says the architecture is not compatible), but it runs a bit slow since it's using Windows x64 emulation. Having native ARM64 would be much better, if possible.

**Comment by jdpurcell** [comment]
I had [an attempt at it](https://github.com/jdpurcell/qView/commit/3e5bb2afa63587952e071e001ce876de576a9cab) but ultimately failed. The problem is, at the moment, Windows on ARM builds must be cross-compiled from an x64 host which involves installing multiple Qt architectures, one for the host and one for the target. I couldn't get them to work together despite various workarounds I tried adapting from other build scripts I searched up on GitHub that were doing Windows ARM64 builds. I'm far from a Qt expert though, maybe @jurplel will have better luck someday.

**Comment by jurplel** [comment]
> I had [an attempt at it](https://github.com/jdpurcell/qView/commit/3e5bb2afa63587952e071e001ce876de576a9cab) but ultimately failed. The problem is, at the moment, Windows on ARM builds must be cross-compiled from an x64 host which involves installing multiple Qt architectures, one for the host and one for the target. I couldn't get them to work together despite various workarounds I tried adapting from other build scripts I [searched up on GitHub](https://github.com/search?l=YAML&q=win64_msvc2019_arm64&type=Code) that were doing Windows ARM64 builds. I'm far from a Qt expert though, maybe @jurplel will have better luck someday.

Thank you for your hard work as always.

I might give this a try some day, but the main bottleneck in qView releases is that the build process is still largely manual, despite hundreds of hours sunk into continuous deployment infrastructure. This is largely because of the plugins.

Hopefully one day I can completely automate this, but I am a ways off from that currently. Until then, I am hesitant to introduce new targets.

**Comment by jurplel** [comment]
If someone wants to make this happen, they can make a PR for the CI here and at my other repo `kimageformats-binaries` (which makes the plugins)
