### ISSUE TITLE
aPNG Support

### ISSUE THREAD

**Issue by NextdoorPsycho** [jurplel/qView#594]
As we advance in the omniplex of the internet universe, more and more people are going to use apng if we like it or not for better quality Gif-like images.  so adding it here seems like a great idea

**Comment by jurplel** [comment]
APNG is actually already supported! ...or at least, it should be.

There is an image format plugin that works for this, but I believe I installed it incorrectly in the release for some platforms. Frustratingly, adding image format plugins is still a very manual process (this is literally the reason there has not been a release in a while).

It should be fixed with https://github.com/jurplel/qView/issues/484
