### ISSUE TITLE
Fix for speed Issue in filename character handling, maybe...?

### ISSUE THREAD

**Issue by walkoverfly** [jurplel/qView#618]
**Environment:**
- OS: Windows 11
- qView version: nightly
- Preceding issue link: https://github.com/jurplel/qView/issues/552

**Information:**
- modified code 

**In the file qvinfodialog.h**

changed from:
void updateInfo();

to:
void adjustWindowSize();
void updateInfo();

**In the file qvinfodialog.cpp**

changed from:
    updateInfo();
    window()->adjustSize();

to:
....
#include \<QTimer\>
....
    updateInfo();
    QTimer::singleShot(0, this, &QVInfoDialog::adjustWindowSize);
}
	
void QVInfoDialog::adjustWindowSize()
{
     window()->adjustSize();
}

- explanation

I don't know why this works.

What I tried before was "QTimer::singleShot(0, this, &updateInfo);"

Instead of getting rid of the delay, it just shifted it somewhere else. Loading of images for files with specific character names has been improved, but opening a separate file info window is slower, as expected....

Then, just in case, I tested "QTimer::singleShot(0, this, &QVInfoDialog::adjustWindowSize);", and both the image file loading and the separate file information window were improved... huh?

When I built it with the nightly version, there was no noticeable performance degradation. The memory and resource usage were also similar.

I'm not a developer, so it's not a strict number, but a feeling.

Anyway, could you please check it out? Because of where I live and the language I speak, I can't avoid this problem...

**Comment by jdpurcell** [comment]
Does this delay happen only the first time you open an image in qView, or subsequent images as well? In other words, if you launch qView, open an image, and then open other images in the same window without exiting qView in between (e.g. by using the left/right arrows on the keyboard to navigate to other images in the same folder), does the delay happen for only the first image or all of them?

**Comment by jdpurcell** [comment]
@walkoverfly Could you please try [the build](https://github.com/jurplel/qView/actions/runs/5981675082?pr=622) from my pull request (#622) and see if it performs similar to your code changes? I think I did basically the same thing, and also skipped updating the info dialog if it isn't visible.

**Comment by jdpurcell** [comment]
@walkoverfly Thank you for testing! I see the problem you mentioned about showing the error text, and I've fixed that with an additional commit.

As for why I am reluctant to put only the `adjustSize` part inside the timer callback, I was worried about glitches such as this:
![infodialog](https://github.com/jurplel/qView/assets/6741660/0e604af9-5222-4e98-a604-4c78a708a3c5)

However, I only noticed that during artificial tests in which I added `QThread::msleep(750)` right before `adjustSize` because I was trying to have an easier way to simulate the problem. If I do realistic testing with a Chinese character in the filename, the visual glitch doesn't happen. So your proposed fix seems good too, but as you mentioned, even I don't fully understand how it works, and I would prefer to go with an approach that can be understood and explained if it works just as well, to reduce the chance of other bugs or side effects.

You can leave the issue open. @jurplel will close it if/when he accepts the pull request.

**Comment by jurplel** [comment]
done!
