### ISSUE TITLE
Crash on quit action, with certain Qt versions and macOS version combinations

### ISSUE THREAD

**Issue by shape55** [jurplel/qView#635]
**Environment:**
- OS: macOS 10.15.7 Catalina
- qView version: 6.1

**Information:**
Just updated to the latest version, and every time I manually quit it crashes:

Here's the crash report:
https://pastebin.com/dAsuA90M

**Comment by jurplel** [comment]
This is a really inconsistent bug that keeps cropping up with certain Qt and macOS version combinations. With qView 6.1 (non-legacy), on the latest version of macOS, the issue does not occur.

There isn't any obvious fix since it requires certain Qt versions in the build process. Older versions cause the issue to appear in newer versions of macOS, if I recall correctly.
